/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SolidityHighlight {
    'code': string;
  }
}

declare global {


  interface HTMLSolidityHighlightElement extends Components.SolidityHighlight, HTMLStencilElement {}
  var HTMLSolidityHighlightElement: {
    prototype: HTMLSolidityHighlightElement;
    new (): HTMLSolidityHighlightElement;
  };
  interface HTMLElementTagNameMap {
    'solidity-highlight': HTMLSolidityHighlightElement;
  }
}

declare namespace LocalJSX {
  interface SolidityHighlight extends JSXBase.HTMLAttributes<HTMLSolidityHighlightElement> {
    'code'?: string;
  }

  interface IntrinsicElements {
    'solidity-highlight': SolidityHighlight;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


